spring.application.name=inbox-housekeeping

# datasource (local docker-compose postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.contexts=dev

housekeeping.error-retention-days=2
housekeeping.archive-batch-size=5000
housekeeping.cron=0 * * * * *
housekeeping.lock-at-most-for=30m
housekeeping.lock-at-least-for=0s
